export enum GrantId {
  /* Platform */
  PlatformKpisManagement = "PLATFORM_KPIS_MANAGEMENT",
  PlatformUsersManagement = "PLATFORM_USERS_MANAGEMENT",
  PlatformOrganizationsManagement = "PLATFORM_ORGANIZATIONS_MANAGEMENT",
  PlatformOrganizationsCanCreate = "PLATFORM_ORGANIZATIONS_CAN_CREATE",
  PlatformOrganizationsCanUpdate = "PLATFORM_ORGANIZATIONS_CAN_UPDATE",
  PlatformOrganizationsCanActivate = "PLATFORM_ORGANIZATIONS_CAN_ACTIVATE",
  PlatformOrganizationsCanSuspend = "PLATFORM_ORGANIZATIONS_CAN_SUSPEND",
  PlatformRolesManagement = "PLATFORM_ROLES_MANAGEMENT",
  PlatformEventsManagement = "PLATFORM_EVENTS_MANAGEMENT",
  PlatformEventsCanCancel = "PLATFORM_EVENTS_CAN_CANCEL",
  PlatformEventsCanPublish = "PLATFORM_EVENTS_CAN_PUBLISH",
  PlatformOfferCanCreate = "PLATFORM_OFFER_CAN_CREATE",
  PlatformOfferCanUpdate = "PLATFORM_OFFER_CAN_UPDATE",
  PlarformUsersCanViewParticipants = "PLATFORM_USERS_CAN_VIEW_PARTICIPANTS",
  PlatformUsersCanViewAdministrators = "PLATFORM_USERS_CAN_VIEW_ADMINISTRATORS",
  /* Organization */
  OrganizationKpisManagement = "ORGANIZATION_KPIS_MANAGEMENT",
  OrganizationEventsManagement = "ORGANIZATION_EVENTS_MANAGEMENT",
  OrganizationEventsCanCreate = "ORGANIZATION_EVENTS_CAN_CREATE",
  OrganizationEventsCanEdit = "ORGANIZATION_EVENTS_CAN_EDIT",
  OrganizationUsersManagement = "ORGANIZATION_USERS_MANAGEMENT",
  OrganizationRolesManagement = "ORGANIZATION_ROLES_MANAGEMENT",
}
